source_dir = "FFmpeg"
x264_source_dir = "x264"
configure_common = [
  "--disable-bzlib",
  "--disable-debug",
  "--disable-doc",
  "--disable-programs",
  "--disable-shared",
  "--disable-vulkan",
  "--disable-vaapi",
  "--disable-hwaccels",
  "--disable-autodetect",
  "--enable-static",
  "--enable-gpl",
  "--disable-everything",
  "--enable-decoder=h264,hevc,vp9,av1,aac,aac_latm,flac,mp3,wav,vorbis,opus",
  "--enable-encoder=libx264,aac,rawvideo",
  "--enable-libx264",
  "--pkg-config-flags=--static",
  "--enable-demuxer=h264,hevc,aac,flv,mov,mpegts,flac,wav,mp3,matroska,ogg",
  "--enable-muxer=h264,adts,mp4,mov,rawvideo,flac,mp3,wav,matroska",
  "--enable-parser=h264,hevc,aac,mpegaudio,vp9,opus",
  "--enable-protocol=file,pipe",
  "--enable-bsf=h264_mp4toannexb",
  "--enable-swscale",
  "--enable-swscale-alpha",
  "--enable-filter=scale",
]
package_libs = [
  "libx264.a",
  "libavcodec.a",
  "libavformat.a",
  "libavutil.a",
  "libswresample.a",
  "libswscale.a",
]
package_layout = "flat"
make_jobs = 0
